source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    BasketChangeView, BasketView, OrderListView, OrderDetailView, OrderCreateView, OrderUpdateView, \
    OrderDeliverView, OrderCancelView, OrderProductCreateView, OrderProductUpdateView, \
    OrderProductDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_detail'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('basket/change/', BasketChangeView.as_view(), name='basket_change'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/deliver/', OrderDeliverView.as_view(), name='order_deliver'),
    path('order/<int:pk>/cancel/', OrderCancelView.as_view(), name='order_cancel'),

    path('order/<int:pk>/add-product/', OrderProductCreateView.as_view(), name='order_add_product'),
    path('order-product/<int:pk>/update/', OrderProductUpdateView.as_view(), name='order_product_update'),
    path('order-product/<int:pk>/delete/', OrderProductDeleteView.as_view(), name='order_product_delete'),
]

source/webapp/models.py
from django.conf import settings
from django.db import models


CATEGORY_CHOICES = (
    ('other', 'Другое'),
    ('food', 'Еда'),
    ('clothes', 'Одежда'),
    ('household', 'Товары для дома'),
)


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Товар')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name='Категория')
    photo = models.ImageField(upload_to='product_images', null=True, blank=True, verbose_name='Фото')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    in_order = models.BooleanField(verbose_name='В наличий', default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


ORDER_STATUS_DELIVERED = 'delivered'
ORDER_STATUS_CANCELED = 'canceled'
ORDER_STATUS_CHOICES = (
    ('new', 'Новый'),
    ('payed', 'Оплачен'),
    ('processing', 'Обработка'),
    (ORDER_STATUS_DELIVERED, 'Доставлен'),
    (ORDER_STATUS_CANCELED, 'Отменён')
)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
                             verbose_name='Пользователь', related_name='orders')
    first_name = models.CharField(max_length=100, verbose_name='Имя', null=True, blank=True)
    last_name = models.CharField(max_length=100, verbose_name='Фамилия', null=True, blank=True)
    email = models.EmailField(max_length=50, verbose_name='Email', null=True, blank=True)
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    products = models.ManyToManyField(Product, through='OrderProduct', through_fields=('order', 'product'),
                                      verbose_name='Товары', related_name='orders')
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0],
                              verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    def __str__(self):
        return "{} ({})".format(self.created_at.strftime('%Y-%m-%d %H:%M:%S'), self.get_status_display())

    def get_total(self):
        total = 0
        for order_product in self.order_products.all():
            total += order_product.get_total()
        return total

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        permissions = [('deliver_order', 'Может доставить заказ')]


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ', related_name='order_products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар', related_name='order_products')
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Количество')

    def __str__(self):
        return "{} - {}".format(self.product, self.order)

    def get_total(self):
        return self.amount * self.product.price

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказах'

source/webapp/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from webapp.models import Order, OrderProduct


class BasketOrderCreateForm(ModelForm):
    def __init__(self, user=None, **kwargs):
        self.user = user
        if user and not user.is_authenticated:
            self.user = None
        super().__init__(**kwargs)

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not first_name and not self.user:
            raise ValidationError('Вы должны авторизоваться либо указать ваше имя!')
        return first_name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email and not self.user:
            raise ValidationError('Вы должны авторизоваться либо указать ваш email!')
        return email

    def save(self, commit=True):
        self.instance.user = self.user
        return super().save(commit)

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone']


class ManualOrderForm(ModelForm):
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not first_name and not self.cleaned_data.get('user'):
            raise ValidationError('Вы должны указать пользователя либо его имя!')
        return first_name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email and not self.cleaned_data.get('user'):
            raise ValidationError('Вы должны указать пользователя либо его email!')
        return email

    class Meta:
        model = Order
        fields = ['user', 'first_name', 'last_name', 'email', 'phone']


class OrderProductForm(ModelForm):
    class Meta:
        model = OrderProduct
        fields = ['product', 'amount']

source/webapp/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView,  UpdateView, DeleteView
from webapp.mixins import StatsMixin
from webapp.models import Product, Order, OrderProduct, ORDER_STATUS_DELIVERED, ORDER_STATUS_CANCELED
from django.http import HttpResponseRedirect
from django.shortcuts import reverse, redirect, get_object_or_404
from webapp.forms import BasketOrderCreateForm, ManualOrderForm, OrderProductForm


class IndexView(StatsMixin, ListView):
    model = Product
    template_name = 'index.html'

    def get_queryset(self):
        return Product.objects.filter(in_order=True)


class ProductView(StatsMixin, DetailView):
    model = Product
    template_name = 'product/detail.html'


class ProductCreateView(PermissionRequiredMixin, StatsMixin, CreateView):
    model = Product
    template_name = 'product/create.html'
    fields = ('name', 'category', 'price', 'photo', 'in_order')
    permission_required = 'webapp.add_product'
    permission_denied_message = "Доступ запрещён"

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class ProductUpdateView(LoginRequiredMixin, StatsMixin, UpdateView):
    model = Product
    template_name = 'product/update.html'
    fields = ('name', 'category', 'price', 'photo', 'in_order')
    context_object_name = 'product'

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class ProductDeleteView(LoginRequiredMixin, StatsMixin, DeleteView):
    model = Product
    template_name = 'product/delete.html'
    success_url = reverse_lazy('webapp:index')
    context_object_name = 'product'

    def delete(self, request, *args, **kwargs):
        product = self.object = self.get_object()
        product.in_order = False
        product.save()
        return HttpResponseRedirect(self.get_success_url())


class BasketChangeView(View):
    def get(self, request, *args, **kwargs):
        products = request.session.get('products', [])
        pk = request.GET.get('pk')
        action = request.GET.get('action')
        next_url = request.GET.get('next', reverse('webapp:index'))

        if action == 'add':
            product = get_object_or_404(Product, pk=pk)
            if product.in_order:
                products.append(pk)
        else:
            for product_pk in products:
                if product_pk == pk:
                    products.remove(product_pk)
                    break

        request.session['products'] = products
        request.session['products_count'] = len(products)
        return redirect(next_url)


class BasketView(StatsMixin, CreateView):
    model = Order
    form_class = BasketOrderCreateForm
    template_name = 'product/basket.html'
    success_url = reverse_lazy('webapp:index')

    def get_context_data(self, **kwargs):
        basket, basket_total = self._prepare_basket()
        kwargs['basket'] = basket
        kwargs['basket_total'] = basket_total
        return super().get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        if self._basket_empty():
            form.add_error(None, 'В корзине отсутствуют товары!')
            return self.form_invalid(form)
        response = super().form_valid(form)
        self._save_order_products()
        self._clean_basket()
        messages.success(self.request, 'Заказ сохранён!')
        return response

    def _prepare_basket(self):
        totals = self._get_totals()
        basket = []
        basket_total = 0

        for pk, qty in totals.items():
            product = Product.objects.get(pk=int(pk))
            total = product.price * qty
            basket_total += total
            basket.append({'product': product, 'qty': qty, 'total': total})
        return basket, basket_total

    def _get_totals(self):
        products = self.request.session.get('products', [])
        totals = {}

        for product_pk in products:
            if product_pk not in totals:
                totals[product_pk] = 0
            totals[product_pk] += 1
        return totals

    def _basket_empty(self):
        products = self.request.session.get('products', [])
        return len(products) == 0

    def _save_order_products(self):
        totals = self._get_totals()
        for pk, qty in totals.items():
            OrderProduct.objects.create(product_id=pk, order=self.object, amount=qty)

    def _clean_basket(self):
        if 'products' in self.request.session:
            self.request.session.pop('products')
        if 'products_count' in self.request.session:
            self.request.session.pop('products_count')


class OrderListView(LoginRequiredMixin, ListView):
    template_name = 'order/list.html'
    context_object_name = 'orders'
    model = Order

    def get_queryset(self):
        if self.request.user.has_perm('webapp.view_order'):
            return Order.objects.all().order_by('-created_at')
        return self.request.user.orders.all().order_by('-created_at')


class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = 'order/detail.html'
    model = Order

    def get_queryset(self):
        if self.request.user.has_perm('webapp.view_order'):
            return Order.objects.all()
        return self.request.user.orders.all()


class OrderCreateView(PermissionRequiredMixin, CreateView):
    model = Order
    form_class = ManualOrderForm
    template_name = 'order/create.html'
    permission_required = 'webapp.add_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


class OrderUpdateView(PermissionRequiredMixin, UpdateView):
    model = Order
    form_class = ManualOrderForm
    template_name = 'order/update.html'
    context_object_name = 'order'
    permission_required = 'webapp.change_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


class OrderDeliverView(PermissionRequiredMixin, View):
    permission_required = 'webapp.deliver_order'

    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs.get('pk'))
        order.status = ORDER_STATUS_DELIVERED
        order.save()
        return redirect('webapp:order_list')


class OrderCancelView(PermissionRequiredMixin, View):
    permission_required = 'webapp.delete_order'

    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs.get('pk'))
        order.status = ORDER_STATUS_CANCELED
        order.save()
        return redirect('webapp:order_list')


class OrderProductCreateView(PermissionRequiredMixin, CreateView):
    model = OrderProduct
    form_class = OrderProductForm
    template_name = 'order_product/create.html'
    permission_required = 'webapp.create_orderproduct'

    def get_context_data(self, **kwargs):
        kwargs['order'] = self.get_order()
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.order = self.get_order()
        return super().form_valid(form)

    def get_order(self):
        return get_object_or_404(Order, pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})


class OrderProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = OrderProduct
    form_class = OrderProductForm
    context_object_name = 'order_product'
    template_name = 'order_product/update.html'
    permission_required = 'webapp.change_orderproduct'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})


class OrderProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = OrderProduct
    template_name = 'order_product/delete.html'
    context_object_name = 'order_product'
    permission_required = 'webapp.delete_orderproduct'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})

source/webapp/templates/order/create.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">Добавить заказ</h1>
    <form method="post" action="{% url 'webapp:order_create' %}">
        {% include 'partial/form.html' %}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
{% endblock %}

source/webapp/templates/order/detail.html
{% extends 'base.html' %}

{% block menu %}
    {% if perms.webapp.change_order %}
        <li class="nav-item"><a class="nav-link" href="{% url 'webapp:order_update' order.pk %}">Изменить</a></li>
    {% endif %}
    {% if perms.webapp.deliver_order %}
        <li class="nav-item"><a class="nav-link" href="{% url 'webapp:order_deliver' order.pk %}">Доставить</a></li>
    {% endif %}
    {% if perms.webapp.delete_order %}
        <li class="nav-item"><a class="nav-link" href="{% url 'webapp:order_cancel' order.pk %}">Отменить</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="text-center">Заказ от {{ order.created_at|date:'Y-m-d H:i:s' }} ({{ order.get_status_display }})</h1>
    <p>
        Имя:
        {% if order.first_name %}
            {{ order.first_name }}
        {% else %}
            {% if order.user %}
                {{ order.user.first_name }}
            {% endif %}
        {% endif %}
        {% if order.last_name %}
            {{ order.last_name }}
        {% else %}
            {% if order.user %}
                {{ order.user.last_name }}
            {% endif %}
        {% endif %}
    </p>
    <p>
        Email:
        {% if order.email %}
            {{ order.email }}
        {% else %}
            {% if order.user.email %}
                {{ order.user.email }}
            {% endif %}
        {% endif %}
    </p>
    <p>Телефон: {{ order.phone }}</p>
    <h3 class="text-center my-3">Товары в заказе</h3>
    <p class="text-center">
        {% if perms.webapp.add_orderproduct %}
            <a href="{% url "webapp:order_add_product" order.pk %}">Добавить товар</a>
        {% endif %}
    </p>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Товар</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Итого</th>
            <th colspan="2" class="text-center">Действия</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order.order_products.all %}
            <tr>
                <td><a href="{% url 'webapp:product_detail' item.product.pk %}">{{ item.product.name }}</a></td>
                <td>{{ item.product.price }}</td>
                <td>{{ item.amount }}</td>
                <td>{{ item.get_total|floatformat:2 }}</td>
                <td>
                    {% if perms.webapp.change_orderproduct %}
                        <a href="{% url 'webapp:order_product_update' item.pk %}">Редактировать</a>
                    {% endif %}
                </td>
                <td>
                    {% if perms.webapp.delete_orderproduct %}
                        <a href="{% url 'webapp:order_product_delete' item.pk %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th colspan="3">Итого:</th>
            <td colspan="3">{{ order.get_total|floatformat:2 }}</td>
        </tr>
        </tfoot>
    </table>
{% endblock %}

source/webapp/templates/order/list.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center mb-3">Заказы</h1>
    {% for order in orders %}
        <div class="card mb-3">
            <div class="card-header">
                <p class="card-text text-right">{{ order.created_at|date:'Y-m-d H:i:s' }} ({{ order.get_status_display }})</p>
            </div>
            <div class="card-body">
                <p class="card-text">
                    Имя:
                    {% if order.first_name %}
                        {{ order.first_name }}
                    {% else %}
                        {% if order.user %}
                            {{ order.user.first_name }}
                        {% endif %}
                    {% endif %}
                    {% if order.last_name %}
                        {{ order.last_name }}
                    {% else %}
                        {% if order.user %}
                            {{ order.user.last_name }}
                        {% endif %}
                    {% endif %}
                </p>
                <p class="card-text">
                    Email:
                    {% if order.email %}
                        {{ order.email }}
                    {% else %}
                        {% if order.user.email %}
                            {{ order.user.email }}
                        {% endif %}
                    {% endif %}
                </p>
                <p class="card-text">Телефон: {{ order.phone }}</p>
            </div>
            <div class="card-footer">
                {% if perms.webapp.view_order or request.user == order.user %}
                    <a class="card-link" href="{% url 'webapp:order_detail' order.pk %}">Просмотреть</a>
                {% endif %}
                {% if perms.webapp.change_order %}
                    <a class="card-link" href="{% url 'webapp:order_update' order.pk %}">Изменить</a>
                {% endif %}
                {% if perms.webapp.deliver_order %}
                    <a class="card-link" href="{% url 'webapp:order_deliver' order.pk %}">Доставить</a>
                {% endif %}
                {% if perms.webapp.delete_order %}
                    <a class="card-link" href="{% url 'webapp:order_cancel' order.pk %}">Отменить</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

source/webapp/templates/order/update.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">Изменить заказ</h1>
    <form method="post" action="{% url 'webapp:order_update' order.pk %}">
        {% include 'partial/form.html' %}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}